import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { BookOpen, FileText } from "lucide-react";

const NoteCard = ({ content, videoUrl, language }) => {
  // Extract video title from URL (simplified)
  const getVideoTitle = (url) => {
    try {
      const urlObj = new URL(url);
      const videoId =
        urlObj.searchParams.get("v") || urlObj.pathname.split("/").pop();
      return `YouTube Video (${videoId})`;
    } catch {
      return "YouTube Video";
    }
  };

  if (!content) return null;

  return (
    <Card className="glass border-white/20 max-w-4xl mx-auto mt-8">
      <CardHeader className="pb-4">
        <div className="flex items-center space-x-3">
          <div className="p-2 rounded-lg bg-primary/20">
            <FileText className="h-5 w-5 text-primary" />
          </div>
          <div>
            <CardTitle className="text-xl text-white">
              Learning Note Generated
            </CardTitle>
            <p className="text-white/60 text-sm">
              {getVideoTitle(videoUrl)} • {language}
            </p>
          </div>
        </div>
      </CardHeader>

      <CardContent className="pt-0">
        <div className="prose prose-invert max-w-none">
          <div
            className="text-white/90 leading-relaxed whitespace-pre-wrap"
            style={{
              fontFamily: "inherit",
              lineHeight: "1.7",
            }}
          >
            {content.split("\n").map((line, index) => {
              // Format different types of content
              if (line.startsWith("# ")) {
                return (
                  <h1
                    key={index}
                    className="text-2xl font-bold text-primary mb-4 mt-6"
                  >
                    {line.replace("# ", "")}
                  </h1>
                );
              }
              if (line.startsWith("## ")) {
                return (
                  <h2
                    key={index}
                    className="text-xl font-semibold text-secondary mb-3 mt-5"
                  >
                    {line.replace("## ", "")}
                  </h2>
                );
              }
              if (line.startsWith("### ")) {
                return (
                  <h3
                    key={index}
                    className="text-lg font-medium text-accent mb-2 mt-4"
                  >
                    {line.replace("### ", "")}
                  </h3>
                );
              }
              if (line.startsWith("• ")) {
                return (
                  <li key={index} className="ml-4 mb-1 list-disc list-inside">
                    {line.replace("• ", "")}
                  </li>
                );
              }
              if (line.startsWith("**") && line.endsWith("**")) {
                return (
                  <p key={index} className="font-semibold mb-2">
                    {line.replace(/\*\*/g, "")}
                  </p>
                );
              }
              if (line.startsWith("`") && line.endsWith("`")) {
                return (
                  <code
                    key={index}
                    className="bg-white/10 px-2 py-1 rounded text-primary"
                  >
                    {line.replace(/`/g, "")}
                  </code>
                );
              }
              if (line.trim() === "") {
                return <br key={index} />;
              }
              return (
                <p key={index} className="mb-2">
                  {line}
                </p>
              );
            })}
          </div>
        </div>

        <div className="mt-6 pt-4 border-t border-white/10">
          <div className="flex items-center text-white/50 text-sm">
            <BookOpen className="h-4 w-4 mr-2" />
            Generated by NoteQuik • {new Date().toLocaleDateString()}
          </div>
        </div>
      </CardContent>
    </Card>
  );
};

export default NoteCard;
